version: '2'
plugins:
  brakeman:
    enabled: true
    checks:
      dynamic_render_path:
        enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 35
        javascript:
exclude_patterns:
- "app/assets/javascripts/**/*.js"
- "spec/dummy"