name: Rubocop
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: 'vips'
        with:
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop
