name: Rubocop
on: push

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        env:
          BUNDLE_WITHOUT: 'vips'
        with:
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop
